title: Tether Docs
description: Documentation for using the Tether tool

# theme: just-the-docs
# remote_theme: pages-themes/minimal@v0.2.0
theme: jekyll-theme-minimal
# theme: just-the-docs

# Conversion
markdown: kramdown
  highlighter: rouge
  lsi: false
  excerpt_separator: "\n\n"
  incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  # _posts
  - scope:
      path: ""
      # type: posts
    values:
      # layout: single
      # author_profile: true
      read_time: true
      # comments: # true
      # comments: true
      # share: true
      # related: true
      # GS show date: https://mmistakes.github.io/minimal-mistakes/docs/configuration/#post-dates
      show_date: true
      toc: true

plugins:
# - jekyll-toc
- jekyll-remote-theme

url: https://pmavros.github.io/Tether

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/pmavros/Tether
show_downloads: true #["" or "false" (unquoted) to indicate whether to provide a download URL]

